spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pgrip
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#physical-strategy and implicit-strategy prevent jpa to create duplicate coulm or default coulums generation in db
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update    
    database: MYSQL
